# Tap
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# Brew
brew "asdf"
brew "bat"
brew "cloc"
brew "docker"
# brew "fswatch"
brew "fzf"
brew "gh"
brew "git"
brew "gource"
brew "jq"
brew "neofetch"
brew "starship"
brew "tldr"
brew "tmux"
brew "yarn"
brew "zsh-syntax-highlighting"
brew "z"
brew "thefuck"

# Cask
cask "1password-cli"
cask "alt-tab"
cask "rancher"
cask "alfred"
cask "visual-studio-code"
cask "intellij-idea"
cask "spotify"
cask "1password"
