#!/bin/zsh

echo --- Enable global MacOS key repeat ---
defaults write -g ApplePressAndHoldEnabled -bool false

echo --- Install Homebrew ---
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo --- Installing from Brewfile ---
brew bundle

for setup in ./*/setup; do
    echo --- $(dirname $setup) ---
    zsh -c "cd $(dirname $setup) && ./setup"
    echo
done
