#!/bin/zsh

alias reload="source $HOME/.zshrc"
alias zshconfig="vim ~/.zshrc"

alias cat="bat"

alias ll='ls -l'
alias la='ls -la'

alias ..='cd ..'

alias codepreview=?fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'