#!/bin/zsh

# Config
alias reload="source $HOME/.zshrc"
alias dotfiles="code ~/dotfiles"

# Listing
alias ll='ls -l'
alias la='ls -la'

# Navigation
alias ..='z ..'
alias ...="z ../.."
alias ....="z ../../.."
alias .....="z ../../../.."

# Misc
alias cat="bat"
alias codepreview=fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'
alias t="tree"
alias ai="omlx launch opencode"
# alias skvis-scripts="/Users/andreas/Documents/code/kartverket/skvis-scripts/skvis-scripts"