#!/bin/zsh

# Config
alias reload="source $HOME/.zshrc"
alias dotfiles="code ~/dotfiles"

# Listing
alias ll='ls -l'
alias la='ls -la'

# Navigation
alias ..='cd ..'
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Misc
alias cat="bat"
alias codepreview=fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'